import "@/styles/globals.css";
import { Nunito } from "next/font/google";

const nunito = Nunito({ subsets: ["latin"] });

export const metadata = {
   title: "Create Next App",
   description: "Generated by create next app",
};

export default function RootLayout({ children, modal }: { children: React.ReactNode; modal: React.ReactNode }) {
   return (
      <html lang="en">
         <body className={nunito.className}>
            <main>{children}</main>
            {modal}
         </body>
      </html>
   );
}
